//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.Photos = new HashSet<Photo>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid CategoryID { get; set; }
        public string Subject { get; set; }
        public string Summary { get; set; }
        public string ContentText { get; set; }
        public bool IsPublish { get; set; }
        public System.DateTime PublishDate { get; set; }
        public int ViewCount { get; set; }
        public System.Guid CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.Guid> UpdateUser { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Photo> Photos { get; set; }
    }
}
